name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build Vite app
      #   run: npm run build

      # - name: Upload via SFTP
      #   uses: easingthemes/ssh-deploy@v4.1.8
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }}
      #     remote-user: ${{ secrets.REMOTE_USER }}
      #     server-ip: ${{ secrets.SERVER_IP }}
      #     remote-path: ${{ secrets.REMOTE_PATH }}
      #     local-path: dist
